version: 0.0
os: linux
files:
  - source: build-output/calculator.war
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
    - location: scripts/restart_tomcat.sh
      timeout: 60
      runas: ubuntu
