version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/ROOT
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/clean_root.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/restart_tomcat.sh
      timeout: 60
      runas: ubuntu
