version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/webapps/ROOT

hooks:
  AfterInstall:
    - location: restart_tomcat.sh
      timeout: 60
      runas: ubuntu   # or the user that owns tomcat files
