version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Running pre-build steps..."
  build:
    commands:
      - echo "Building..."
      - mvn package
  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - 'target/*.jar'
  discard-paths: no
