version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  build:
    commands:
      - echo Building calculator.war...
      - mvn clean package
      - echo Creating deployment bundle...
      - mkdir -p deployment_bundle/scripts
      - cp target/calculator.war deployment_bundle/
      - cp appspec.yml deployment_bundle/
      - cp scripts/*.sh deployment_bundle/scripts/
      - cd deployment_bundle
      - zip -r ../calculator-deployment.zip .
      - cd ..

artifacts:
  files:
    - calculator-deployment.zip
