version: 0.2

phases:
  install:
    commands:
      - echo "Installing any needed tools..."
      # You might install npm packages if needed:
      # - npm install
  build:
    commands:
      - echo "Building frontend application..."
      # For simple HTML/JS projects, you might just:
      # - Validate files exist
      - ls -la
      # - Minify CSS/JS if needed
      # - Run tests if you have any
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'  # This packages all your files
  discard-paths: no
