version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies (if any)...

  pre_build:
    commands:
      - echo Preparing build...
      - mkdir -p build-output/WEB-INF

  build:
    commands:
      - echo Copying source files to build-output directory...
      - cp index.html style.css script.js build-output/
      - cp -r WEB-INF build-output/
      - echo Packaging WAR file...
      - cd build-output
      - jar -cvf calculator.war *
      - cd ..

  post_build:
    commands:
      - echo Build complete. WAR file created.

artifacts:
  files:
    - build-output/calculator.war
